# TODO: Boolean inputs don't work (https://github.com/actions/runner/issues/2238)

name: 'Build Docker image'
inputs:
  checkout:
    description: 'Whether to checkout code'
    required: false
    default: 'true'
  multi-platforms:
    description: 'Whether to build for multiple platforms'
    required: false
    default: 'false'
  tags:
    description: 'Tags'
    required: 'true'
  labels:
    description: 'Labels'
    required: 'true'
  annotations:
    description: 'Annotations'
    required: 'true'
  push:
    description: 'Push or export locally'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout
      if: inputs.checkout == 'true'
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        sparse-checkout: src
        persist-credentials: false
        show-progress: false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20
      with:
        version: https://github.com/docker/buildx.git#30feaa1a915b869ebc2eea6328624b49facd4bfb
        driver-opts: image=moby/buildkit:v0.12.4@sha256:0e5755bb0a836068ffe491e2d04d44815a747910e7a14259810b22ac57189bc3
    # - name: Set up QEMU
      # if: inputs.multi-platforms == 'true'
      # uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7
      # with:
        # image: tonistiigi/binfmt:qemu-v6.2.0@sha256:85683def11494bc0055d98dd1081e73cb5e70bbc1ae532be3d12cf054e2b11f1
        # platforms: arm64
    - name: Build Docker image
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      with:
        # platforms: ${{ inputs.multi-platforms == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        context: src
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        annotations: ${{ inputs.annotations }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        outputs: ${{ inputs.push == 'true' && 'type=registry' || 'type=docker,dest=/tmp/image.tar' }}
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
