# TODO: Boolean inputs don't work (https://github.com/actions/runner/issues/2238)

name: 'Build Docker image'
inputs:
  checkout:
    description: 'Whether to checkout code'
    required: false
    default: 'true'
  multi-platforms:
    description: 'Whether to build for multiple platforms'
    required: false
    default: 'false'
  tags:
    description: 'Tags'
    required: 'true'
  labels:
    description: 'Labels'
    required: 'true'
  push:
    description: 'Push or export locally'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout
      if: inputs.checkout == 'true'
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        sparse-checkout: src
        persist-credentials: false
        show-progress: false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      with:
        version: https://github.com/docker/buildx.git#9872040b6626fb7d87ef7296fd5b832e8cc2ad17
        driver-opts: image=moby/buildkit:v0.12.2@sha256:8ea9857f95c2a0402c245bb0e94f36e2b5b4a1cb05e7ed322c213ed50607ce62
    # - name: Set up QEMU
      # if: inputs.multi-platforms == 'true'
      # uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7
      # with:
        # image: tonistiigi/binfmt:qemu-v6.2.0@sha256:85683def11494bc0055d98dd1081e73cb5e70bbc1ae532be3d12cf054e2b11f1
        # platforms: arm64
    - name: Build Docker image
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
      with:
        # platforms: ${{ inputs.multi-platforms == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        context: src
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        outputs: ${{ inputs.push == 'true' && 'type=registry' || 'type=docker,dest=/tmp/image.tar' }}
