name: 'Setup Node'
inputs:
  working-directory:
    description: 'Working directory for installing dependencies'
    required: false
    default: 'src'

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381
      with:
        node-version: 18.16.0
        cache: 'npm'
        cache-dependency-path: test/package-lock.json
        registry-url: 'https://npm.pkg.github.com/'
    # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#use-private-packages
    - name: Install Node dependencies
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Run post-install scripts
      run: npm rebuild && npm run prepare --if-present
      shell: bash
      working-directory: ${{ inputs.working-directory }}
