name: 'Test Docker image'
inputs:
  code:
    description: 'Code to run'
    required: true
  allowed-endpoints:
    description: 'Allowed endpoints'
    required: false
    default: >
      api.github.com:443
      github.com:443
      registry-1.docker.io:443
      auth.docker.io:443
      production.cloudflare.docker.com:443
  working-directory:
    description: 'Working directory'
    required: false
    default: test

runs:
  using: "composite"
  steps:
    - name: Harden runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: ${{ inputs.allowed-endpoints }}
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        persist-credentials: false
        show-progress: false
    - name: Download Docker image
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: Docker image
        path: /tmp
    - name: Load image
      run: docker load --input /tmp/image.tar
      shell: bash
    - name: Run code
      run: eval "$CODE"
      env:
        CODE: ${{ inputs.code }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
