name: 'Test Docker image'
inputs:
  code:
    description: 'Code to run'
    required: true
  allowed-endpoints:
    description: 'Allowed endpoints'
    required: false
    default: >
      api.github.com:443
      github.com:443
      registry-1.docker.io:443
      auth.docker.io:443
      production.cloudflare.docker.com:443
  working-directory:
    description: 'Working directory'
    required: false
    default: test

runs:
  using: "composite"
  steps:
    - name: Harden runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: ${{ inputs.allowed-endpoints }}
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        persist-credentials: false
        show-progress: false
    - name: Download Docker image
      uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85
      with:
        name: Docker image
        path: /tmp
    - name: Load image
      run: docker load --input /tmp/image.tar
      shell: bash
    - name: Run code
      run: eval "$CODE"
      env:
        CODE: ${{ inputs.code }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
