name: 'Run unit tests'
inputs:
  node-code-pre-test:
    description: 'Code to run pre-test'
    required: false
  report:
    description: 'Report path'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: warriors-life/.warriors-life-workflows/setup-node@dev
      with:
        working-directory: test
    - name: Run pre-tests code
      run: eval "$CODE"
      env:
        CODE: ${{ inputs.node-code-pre-test }}
      shell: bash
      working-directory: test
    - name: Run unit tests
      run: ${{ inputs.report && format('npm test -- --ci --json --outputFile="{0}"', inputs.report) || 'npm test' }}
      env:
        NODE_ENV: ${{ (startsWith(github.ref, 'ref/heads/release') || startsWith(github.base_ref, 'ref/heads/release')) && 'production' || 'development' }}
      shell: bash
      working-directory: test
