name: Build

on:
  workflow_call:
    inputs:
      node-code-pre-test:
        required: false
        type: string
    secrets:
      SNYK_TOKEN:
        required: false
      NPM_TOKEN:
        required: false

permissions: {}

jobs:
  call-workflow:
    uses: ./.github/workflows/build-general.yml
    secrets: inherit
    permissions:
      security-events: write
      actions: read
      contents: read
      issues: read
      pull-requests: read
    with:
      node-code-pre-test: ${{ inputs.node-code-pre-test }}

  push:
    if: github.ref_type == 'tag'
    needs: call-workflow
    name: Publish package in the registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            ghcr.io:443
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          sparse-checkout: src
          persist-credentials: false
          show-progress: false
      - name: Setup Node # TODO: do we need this? maybe this is required when we're publishing package that has GPR dependencies?
        uses: warriors-life/.warriors-life-workflows/setup-node@dev
      - name: Publish package to GPR
        uses: JS-DevTools/npm-publish@fe72237be0920f7a0cafd6a966c9b929c9466e9b
        with:
          registry: 'https://npm.pkg.github.com/'
          token: ${{ github.token }}
          package: src
          provenance: true
      - name: Publish package to NPM
        if: "!github.event.repository.private"
        uses: JS-DevTools/npm-publish@fe72237be0920f7a0cafd6a966c9b929c9466e9b
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: src
          provenance: true

  release:
    if: github.ref_type == 'tag'
    needs: push
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            uploads.github.com:443
            github.com:443
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          persist-credentials: false
          show-progress: false
      - name: Setup Node # TODO: do we need this? maybe this is required when we're publishing package that has GPR dependencies?
        uses: warriors-life/.warriors-life-workflows/setup-node@dev
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@4db7ff8e9cc8a442ab103fd3ddfaebd0f8f36e4c
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Get archive name
        id: archive-name
        run: |
          echo "name=$repository-${tag#v}" >> $GITHUB_OUTPUT
        env:
          tag: ${{ github.ref_name }}
          repository: ${{ github.event.repository.name }}
      - name: Sign files
        run: |
          git -c tar.tar.gz.command='gzip -cn' archive --format=tar.gz --prefix="$archivename/" -o "../$archivename.tar.gz" "$tag"
          gpg --armor --detach-sign "../$archivename.tar.gz"
          npm pack src/
          gpg --armor --detach-sign *.tgz
        env:
          tag: ${{ github.ref_name }}
          archivename: ${{ steps.archive-name.outputs.name }}
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            *.tgz
            *.tgz.asc
            ../${{ steps.archive-name.outputs.name }}.tar.gz.asc
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
