# TODO: maybe cache actions/checkout's output

name: General tests

on:
  workflow_call:
    inputs:
      node-code-pre-test:
        required: false
        type: string
    secrets:
      SNYK_TOKEN:
        required: false
    outputs:
      run-snyk:
        value: ${{ jobs.run-snyk.outputs.run-snyk }}

permissions: {}

jobs:
  scorecard:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev'
    name: Check supply chain with Scorecard
    permissions:
      security-events: write
      actions: read
      contents: read
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            auth.docker.io:443
            index.docker.io:443
            api.osv.dev:443
            bestpractices.dev:443
            bestpractices.coreinfrastructure.org:443
            oss-fuzz-build-logs.storage.googleapis.com:443
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          persist-credentials: false
          show-progress: false
      - name: Run analysis
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031
        with:
          results_file: scorecard.sarif
          results_format: sarif
      - name: Upload output
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Scorecard
          path: scorecard.sarif
      - name: Upload SARIF to dashboard
        if: "!github.event.repository.private"
        uses: github/codeql-action/upload-sarif@f31a31c052207cc13b328d6295c5b728bb49568c
        with:
          sarif_file: scorecard.sarif
          category: Scorecard

  dependency-review:
    if: "!github.event.repository.private"
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          persist-credentials: false
          show-progress: false
      - name: Dependency review
        uses: actions/dependency-review-action@f6fff72a3217f580d5afd49a46826795305b63c7
        with:
          base-ref: ${{ github.base_ref || github.event.before }}
          head-ref: ${{ github.head_ref || github.event.after }}

  codeql:
    if: "!github.event.repository.private"
    name: CodeQL scan
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            uploads.github.com:443
            github.com:443
            objects.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          persist-credentials: false
          show-progress: false
      - name: Init
        uses: github/codeql-action/init@f31a31c052207cc13b328d6295c5b728bb49568c
      - name: Scan
        uses: github/codeql-action/analyze@f31a31c052207cc13b328d6295c5b728bb49568c

  run-snyk:
    name: Run Snyk?
    runs-on: ubuntu-latest
    outputs:
      run-snyk: ${{ steps.set-outputs.outputs.run-snyk }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: ''
      - name: Set outputs
        id: set-outputs
        run: |
          echo "run-snyk=${{ secrets.SNYK_TOKEN != '' }}" >> $GITHUB_OUTPUT

  snyk-js:
    if: needs.run-snyk.outputs.run-snyk == 'true'
    needs: run-snyk
    name: Check JS code for vulnerabilities with Snyk
    permissions:
      security-events: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            api.snyk.io:443
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          persist-credentials: false
          show-progress: false
      - name: Run Snyk
        uses: snyk/actions/node@b98d498629f1c368650224d6d212bf7dfa89e4bf
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-js.sarif --all-projects
        continue-on-error: true
      - name: Upload output
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Snyk (JS)
          path: snyk-js.sarif
      - name: Upload SARIF to dashboard
        if: "!github.event.repository.private"
        uses: github/codeql-action/upload-sarif@f31a31c052207cc13b328d6295c5b728bb49568c
        with:
          category: Snyk (JS)
          sarif_file: snyk-js.sarif

  test-unit:
    if: "inputs.node-code-pre-test != 'DISABLE'"
    name: Run unit tests
    permissions:
      contents: read
    defaults:
      run:
        working-directory: test
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          persist-credentials: false
          show-progress: false
      - name: Setup Node
        uses: warriors-life/.warriors-life-workflows/setup-node@dev
        with:
          working-directory: test
      - name: Run pre-tests code
        run: eval "$CODE"
        env:
          CODE: ${{ inputs.node-code-pre-test }}
      - name: Run unit tests
        run: npm test
        env:
          NODE_ENV: ${{ (startsWith(github.ref, 'ref/heads/release') || startsWith(github.base_ref, 'ref/heads/release')) && 'production' || 'development' }}
