name: Build

on:
  workflow_call:
    inputs:
      node-code-pre-test:
        required: false
        type: string
    secrets:
      SNYK_TOKEN:
        required: false
      NPM_TOKEN:
        required: false

permissions: {}

jobs:
  call-workflow:
    uses: ./.github/workflows/build-general.yml
    secrets: inherit
    permissions:
      security-events: write
      actions: read
      contents: read
      issues: read
      pull-requests: read
    with:
      node-code-pre-test: DISABLE

  test-unit:
    if: "inputs.node-code-pre-test != 'DISABLE'"
    needs: call-workflow
    name: Run unit tests
    permissions:
      pull-requests: write
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          persist-credentials: false
          show-progress: false
      - name: Run unit tests
        uses: warriors-life/.warriors-life-workflows/run-unit-tests@dev
        with:
          node-code-pre-test: ${{ inputs.node-code-pre-test }}
          report: coverage/coverage.json
      - name: Upload coverage file
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: Coverage
          path: test/coverage/coverage.json
      - name: Move coverage file
        run: mv test/coverage/coverage.json /tmp
      - name: Checkout base ref
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          persist-credentials: false
          show-progress: false
          ref: ${{ github.base_ref || 'dev' }}
      - name: Run units tests on base
        uses: warriors-life/.warriors-life-workflows/run-unit-tests@dev
        with:
          node-code-pre-test: ${{ inputs.node-code-pre-test }}
          report: coverage/coverage.json
      - id: coverage-report
        name: Generate coverage report
        uses: ArtiomTr/jest-coverage-report-action@d438b94580c2c47599ce7abc62d26d1acd1661eb
        with:
          coverage-file: /tmp/coverage.json
          base-coverage-file: test/coverage/coverage.json
          output: ${{ github.event_name == 'pull_request' && 'comment' || 'report-markdown' }}
      - name: Show coverage report
        if: "github.event_name != 'pull_request'"
        run: echo "$REPORT" >> $GITHUB_STEP_SUMMARY
        env:
          REPORT: ${{ steps.coverage-report.outputs.report }}

  push:
    if: github.ref_type == 'tag'
    needs: test-unit
    name: Publish package in the registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            *.sigstore.dev:443
            npm.pkg.github.com:443
            github.com:443
            registry.npmjs.org:443
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          sparse-checkout: src
          persist-credentials: false
          show-progress: false
      - name: Setup Node # TODO: do we need this? maybe this is required when we're publishing package that has GPR dependencies?
        uses: warriors-life/.warriors-life-workflows/setup-node@dev
      - name: Move README and license
        run: mv README.md src && mv LICENSE src
      - name: Publish package to NPM
        if: "!github.event.repository.private"
        uses: JS-DevTools/npm-publish@4b07b26a2f6e0a51846e1870223e545bae91c552
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: src
          provenance: true
          access: public
      - name: Modify package name
        uses: maxgfr/github-change-json@8f5aff1c3cabbd646b9896a5c1ca74c0aa72ece0
        with:
          key: name
          value: ${{ format('@{0}', github.repository) }}
          path: src/package.json
      - name: Publish package to NPM (scoped)
        if: "!github.event.repository.private"
        uses: JS-DevTools/npm-publish@4b07b26a2f6e0a51846e1870223e545bae91c552
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: src
          provenance: true
          access: public
      - name: Publish package to GPR
        uses: JS-DevTools/npm-publish@4b07b26a2f6e0a51846e1870223e545bae91c552
        with:
          registry: 'https://npm.pkg.github.com/'
          token: ${{ github.token }}
          package: src
          provenance: ${{ !github.event.repository.private }}
          access: ${{ github.event.repository.private && 'restricted' || 'public' }}

  release:
    if: github.ref_type == 'tag'
    needs: push
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            uploads.github.com:443
            github.com:443
            registry.npmjs.org:443
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          persist-credentials: false
          show-progress: false
      - name: Setup Node # TODO: do we need this? maybe this is required when we're publishing package that has GPR dependencies?
        uses: warriors-life/.warriors-life-workflows/setup-node@dev
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@4a5a562549e21065f6791b32ec5415bd33045cd2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Get archive name
        id: archive-name
        run: |
          echo "name=$repository-${tag#v}" >> $GITHUB_OUTPUT
        env:
          tag: ${{ github.ref_name }}
          repository: ${{ github.event.repository.name }}
      - name: Sign files
        run: |
          git -c tar.tar.gz.command='gzip -cn' archive --format=tar.gz --prefix="$archivename/" -o "../$archivename.tar.gz" "$tag"
          gpg --armor --detach-sign "../$archivename.tar.gz"
          npm pack src/
          gpg --armor --detach-sign *.tgz
        env:
          tag: ${{ github.ref_name }}
          archivename: ${{ steps.archive-name.outputs.name }}
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            *.tgz
            *.tgz.asc
            ../${{ steps.archive-name.outputs.name }}.tar.gz.asc
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
