name: Update release branch from dev

on:
  workflow_call:

permissions: {}

concurrency:
  group: update-template
  cancel-in-progress: true

jobs:
  update-branch:
    name: Update release branch from dev

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0

      - name: Update
        run: |
          git checkout release
          git branch -m release dummy
          git branch -m dev release
          git push -f origin release
