name: Update release branch from dev

on:
  workflow_call:

permissions: {}

concurrency:
  group: update-template
  cancel-in-progress: true

jobs:
  update-branch:
    name: Update release branch from dev

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Update
        run: |
          git checkout release
          git merge dev
          git push
