name: Update release branch from dev

on:
  workflow_call:

permissions: {}

concurrency:
  group: update-template
  cancel-in-progress: true

jobs:
  update-branch:
    name: Update release branch from dev

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0

      - name: Update
        run: |
          git checkout release
          git merge dev
          git push
